name: ResidenceSlimefunCompat
version: 1.0.0
main: com.bekvon.bukkit.residence.slimeFun.CompatibilityPlugin
api-version: 1.13
authors: [Compatibility]
description: Compatibility layer for Residence plugin to work with old Slimefun4 (me.mrCookieSlime version)
website: https://github.com/andjie98/Slimefun4

depend: [Slimefun]
softdepend: [Residence, CMILib]

load: STARTUP

commands:
  rslimefun:
    description: Reload Residence Slimefun compatibility
    usage: /rslimefun reload
    permission: rslimefun.reload

permissions:
  rslimefun.reload:
    description: Allows you to reload Residence Slimefun compatibility
    default: op
